/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package serveur_data_analysis;

/**
 *
 * @author renardN
 */
public class MainFrame extends javax.swing.JFrame {
    
    MainServer ms;

    /**
     * Creates new form FenêtrePrincipale
     */
    public MainFrame() {
        initComponents();
        ms = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanelEnvoi = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLogServeur = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonDemarrage = new javax.swing.JButton();
        jButtonArrêt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Serveur_Data_Analysis");
        getContentPane().add(jLabel1);

        jPanelEnvoi.setLayout(new java.awt.GridLayout(0, 1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOG SERVEUR");
        jPanelEnvoi.add(jLabel2);
        jPanelEnvoi.add(jTextFieldLogServeur);

        getContentPane().add(jPanelEnvoi);

        jPanelButton.setLayout(new java.awt.GridLayout(1, 0));

        jButtonDemarrage.setText("Démarrage");
        jButtonDemarrage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDemarrageActionPerformed(evt);
            }
        });
        jPanelButton.add(jButtonDemarrage);

        jButtonArrêt.setText("Arrêt");
        jButtonArrêt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArrêtActionPerformed(evt);
            }
        });
        jPanelButton.add(jButtonArrêt);

        getContentPane().add(jPanelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDemarrageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDemarrageActionPerformed
        ms = new MainServer(this);
        ms.open();
    }//GEN-LAST:event_jButtonDemarrageActionPerformed

    private void jButtonArrêtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArrêtActionPerformed
        if(ms != null)
            ms.close();
        System.exit(0);
    }//GEN-LAST:event_jButtonArrêtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArrêt;
    private javax.swing.JButton jButtonDemarrage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelEnvoi;
    private javax.swing.JTextField jTextFieldLogServeur;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextFieldEnvoi
     */
    public javax.swing.JTextField getjTextFieldLogServeur() {
        return jTextFieldLogServeur;
    }
}
