/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopapp;

import Protocol.BaseRequest;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author cam_i
 */
public class MainWindow extends javax.swing.JFrame {

    private Socket socket;
    private ObjectOutputStream outputStream;
    private ObjectInputStream inputStream;
    private boolean isDataScientist;
    
    /**
     * Creates new form MainWindow
     * @param host
     * @param port
     * @throws java.io.IOException
     */
    public MainWindow(String host,int port) throws IOException {
        initComponents();
        
        socket = new Socket(host,port);
        outputStream = new ObjectOutputStream(socket.getOutputStream());
        inputStream = new ObjectInputStream(socket.getInputStream());
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                try {
                    stop();
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    public boolean login()
    {
        LoginDialog dialog = new LoginDialog(this,true,inputStream,outputStream);
        dialog.setVisible(true);
        return dialog.isOk();
    }
    
    public void stop() throws IOException
    {
        BaseRequest req = new BaseRequest();
        req.setId(BaseRequest.LOGOUT);
        
        outputStream.writeObject(req);
        
        socket.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        viewPane = new javax.swing.JPanel();
        viewTabbedPane = new javax.swing.JTabbedPane();
        cahPane = new javax.swing.JPanel();
        anovaPane = new javax.swing.JPanel();
        acmPane = new javax.swing.JPanel();
        regPane = new javax.swing.JPanel();
        doPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DesktoppApp");

        mainTabbedPane.setName("View BigData"); // NOI18N

        viewPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout cahPaneLayout = new javax.swing.GroupLayout(cahPane);
        cahPane.setLayout(cahPaneLayout);
        cahPaneLayout.setHorizontalGroup(
            cahPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        cahPaneLayout.setVerticalGroup(
            cahPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        viewTabbedPane.addTab("Bénéfices mensuels", cahPane);

        javax.swing.GroupLayout anovaPaneLayout = new javax.swing.GroupLayout(anovaPane);
        anovaPane.setLayout(anovaPaneLayout);
        anovaPaneLayout.setHorizontalGroup(
            anovaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        anovaPaneLayout.setVerticalGroup(
            anovaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        viewTabbedPane.addTab("Routes commerciales", anovaPane);

        javax.swing.GroupLayout acmPaneLayout = new javax.swing.GroupLayout(acmPane);
        acmPane.setLayout(acmPaneLayout);
        acmPaneLayout.setHorizontalGroup(
            acmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        acmPaneLayout.setVerticalGroup(
            acmPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        viewTabbedPane.addTab("Routes particulières", acmPane);

        javax.swing.GroupLayout regPaneLayout = new javax.swing.GroupLayout(regPane);
        regPane.setLayout(regPaneLayout);
        regPaneLayout.setHorizontalGroup(
            regPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 808, Short.MAX_VALUE)
        );
        regPaneLayout.setVerticalGroup(
            regPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        viewTabbedPane.addTab("Retards", regPane);

        viewPane.add(viewTabbedPane, java.awt.BorderLayout.PAGE_START);
        viewTabbedPane.getAccessibleContext().setAccessibleName("");

        mainTabbedPane.addTab("View BigData", viewPane);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("TO DO");

        javax.swing.GroupLayout doPaneLayout = new javax.swing.GroupLayout(doPane);
        doPane.setLayout(doPaneLayout);
        doPaneLayout.setHorizontalGroup(
            doPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(743, Short.MAX_VALUE))
        );
        doPaneLayout.setVerticalGroup(
            doPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(526, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Do BigData", doPane);

        getContentPane().add(mainTabbedPane, java.awt.BorderLayout.CENTER);
        mainTabbedPane.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setDataScientist(boolean isdatascientist) {
        isDataScientist = isdatascientist;
        
        mainTabbedPane.setEnabledAt(1, isdatascientist);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acmPane;
    private javax.swing.JPanel anovaPane;
    private javax.swing.JPanel cahPane;
    private javax.swing.JPanel doPane;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel regPane;
    private javax.swing.JPanel viewPane;
    private javax.swing.JTabbedPane viewTabbedPane;
    // End of variables declaration//GEN-END:variables
}
